Update file_copy_test.yaml
JIRA-1234

diff --git a/.github/workflows/file_copy_test.yaml b/.github/workflows/file_copy_test.yaml
--- a/.github/workflows/file_copy_test.yaml
+++ b/.github/workflows/file_copy_test.yaml
@@ -27,12 +27,18 @@ jobs:
         run: |
           echo "Commit message=${{ github.event.head_commit.message }}"
           echo "Ref=${{ github.event.ref}}"
-      - name: Check if commit has contains JIRA id
+      - name: Check if commit and branch name contains JIRA id
         run: |
           if [[ "${{ github.event.head_commit.message }}" == *"JIRA-"* ]]; then
             echo "Commit has JIRA id, check ok"
           else
-            echo "Variable does not contain JIRA id"
+            echo "Commit message does not contain JIRA id, check failed"
+            exit 1
+          fi
+          if [[ "${{ github.event.ref }}" == *"JIRA-"* ]]; then
+            echo "Branch name contains IRA id, check ok"
+          else
+            echo "Branch name does not contain JIRA id, check failed"
             exit 1
           fi
       - name: Final check...
